name = "aether"
license = "MIT"
licenselink = "https://github.com/josephhutch/aether/blob/master/LICENSE.md"
description = "aether is a blog theme that emphasizes motion, material, and depth as design elements to highlight the content of your site"
homepage = "https://github.com/josephhutch/aether"
categories = ["Blog", "Personal", "Responsive", "Minimal", "Simple", "Clean", "Material Design"]
features = ["Responsive", "Highlight.js"]
min_version = "0.26"

[author]
name = "Joe Hutchinson"
homepage = "https://www.joehutch.com"
